spring:
  #redis的配置
  redis:
    host: 192.168.124.71
    port: 6379
    password: 123456
    database: 5
    #jedis 连接池的配置
    jedis:
      pool:
        max-active: 8
        max-wait: 1000
        max-idle: 8
        min-idle: 0
